Allow verification of OS image.

diff --git a/plugins/playbooks/gitops/roles/gitops_tools/templates/50_mender_ansible b/plugins/playbooks/gitops/roles/gitops_tools/templates/50_mender_ansible
--- a/plugins/playbooks/gitops/roles/gitops_tools/templates/50_mender_ansible
+++ b/plugins/playbooks/gitops/roles/gitops_tools/templates/50_mender_ansible
@@ -12,7 +12,7 @@ WORKDIR="/home/${GITOPS_USER_NAME}"
 print_error()
 {
     local MESSAGE="${1}"
-    >&2 echo -e "Error: ${MESSAGE}"
+    >&2 echo -e "${0}: Error: ${MESSAGE}"
 }
 
 unexpected_exit()
@@ -32,7 +32,7 @@ clean_up()
 
 if [ $# -ne 1 ]
 then
-    >&2 echo "Error: This script is expecting exactly one argument (the configuration file)."
+    print_error "This script is expecting exactly one argument (the configuration file)."
     exit 2
 fi
 
@@ -40,19 +40,19 @@ CONFIG="$1"
 
 if [ ! -e "${CONFIG}" ]
 then
-    >&2 echo "Error: The configuration file ${CONFIG} does not exist."
+    print_error "The configuration file ${CONFIG} does not exist."
     exit 1
 fi
 
 if [ ! -s "${CONFIG}" ]
 then
-    >&2 echo "Error: The configuration file ${CONFIG} is empty."
+    print_error "The configuration file ${CONFIG} is empty."
     exit 1
 fi
 
 if ! jq -e . >/dev/null 2>&1 < "${CONFIG}"
 then
-    >&2 echo "Error: Failed to parse ${CONFIG}."
+    print_error "Failed to parse ${CONFIG}."
     exit 1
 fi
 
@@ -66,6 +66,19 @@ if ! PLAYBOOK_VERSION="$(jq -r -e .playbook_version < "${CONFIG}")"
 then
     echo "${0}: Nothing to do as there is no 'playbook_version'."
     exit 0
+fi
+
+if ! EXPECTED_OS_IMAGE="$(jq -r -e .expected_os_image < "${CONFIG}")"
+then
+    echo "${0}: Skipping OS image check!"
+else
+    CURRENT_OS_IMAGE=$(cut -d'=' -f2 < /etc/mender/artifact_info)
+    if [ "${CURRENT_OS_IMAGE}" != "${EXPECTED_OS_IMAGE}" ]
+    then
+        print_error "The current OS image (${CURRENT_OS_IMAGE}) does not match the expected one (${EXPECTED_OS_IMAGE})!"
+        echo "${0}: Possible reason: The previous OS image deployment failed."
+        exit 1
+    fi
 fi
 
 TEMPDIR=$(${GITOPS_USER} mktemp -p "${WORKDIR}" -d -t .tmp.XXXXXXXX)
@@ -91,7 +104,7 @@ done
 
 if [[ "${PLAYBOOK_URL_REACHABLE}" -eq 0 ]]
 then
-    >&2 echo "Error: Failed to fetch playbook '${PLAYBOOK_URL}'."
+    print_error "Failed to fetch playbook '${PLAYBOOK_URL}'."
     exit 1
 fi
 
